version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepass123
      - N8N_HOST=n8n-onrender
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n-onrender.onrender.com
    volumes:
      - /data:/home/node/.n8n
